apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ printf "%s-discovery" (include "rabbitmq-ha.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ template "rabbitmq-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: http-dash
      protocol: TCP
      port: {{ .Values.rabbitmqManagerPort }}
      targetPort: http-dash
    - name: tcp-amqp
      protocol: TCP
      port: {{ .Values.rabbitmqNodePort }}
      targetPort: tcp-amqp
    - name: tcp-epmd
      protocol: TCP
      port: {{ .Values.rabbitmqEpmdPort }}
      targetPort: tcp-epmd
    {{- if .Values.rabbitmqSTOMPPlugin.enabled }}
    - name: tcp-stomp
      protocol: TCP
      port: 61613
      targetPort: tcp-stomp
    - name: tcp-stomp-ssl
      protocol: TCP
      port: 61614
      targetPort: tcp-stomp-ssl
    {{- end }}
    {{- if .Values.rabbitmqWebSTOMPPlugin.enabled }}
    - name: http-stomp-ws
      protocol: TCP
      port: 15674
      targetPort: http-stomp-ws
    {{- end }}
    {{- if .Values.rabbitmqMQTTPlugin.enabled }}
    - name: tcp-mqtt
      protocol: TCP
      port: 1883
      targetPort: tcp-mqtt
    - name: tcp-mqtt-ssl
      protocol: TCP
      port: 8883
      targetPort: tcp-mqtt-ssl
    {{- end }}
    {{- if .Values.rabbitmqWebMQTTPlugin.enabled }}
    - name: http-mqtt-ws
      protocol: TCP
      port: 15675
      targetPort: http-mqtt-ws
    {{- end }}
    {{- if .Values.rabbitmqAmqpsSupport.enabled }}
    - name: tcp-amqps
      protocol: TCP
      port: {{ .Values.rabbitmqAmqpsSupport.amqpsNodePort }}
      targetPort: tcp-amqps
    {{- end }}
  publishNotReadyAddresses: true
  selector:
    app: {{ template "rabbitmq-ha.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
