apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "rabbitmq-ha.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ template "rabbitmq-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
{{- if ne .Values.service.type "NodePort" }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - name: http-dash
      protocol: TCP
      port: {{ .Values.rabbitmqManagerPort }}
      {{- if eq .Values.service.type "NodePort" "LoadBalancer" }}
      nodePort: {{ .Values.service.managerNodePort }}
      {{- end }}
      targetPort: http-dash
    - name: tcp-amqp
      protocol: TCP
      port: {{ .Values.rabbitmqNodePort }}
      {{- if eq .Values.service.type "NodePort" "LoadBalancer" }}
      nodePort: {{ .Values.service.amqpNodePort }}
      {{- end }}
      targetPort: tcp-amqp
    - name: tcp-epmd
      protocol: TCP
      port: {{ .Values.rabbitmqEpmdPort }}
      {{- if eq .Values.service.type "NodePort" "LoadBalancer" }}
      nodePort: {{ .Values.service.epmdNodePort }}
      {{- end }}
      targetPort: tcp-epmd
    {{- if .Values.rabbitmqSTOMPPlugin.enabled }}
    - name: tcp-stomp
      protocol: TCP
      port: 61613
      targetPort: tcp-stomp
    - name: tcp-stomp-ssl
      protocol: TCP
      port: 61614
      targetPort: tcp-stomp-ssl
    {{- end }}
    {{- if .Values.rabbitmqWebSTOMPPlugin.enabled }}
    - name: http-stomp-ws
      protocol: TCP
      port: 15674
      targetPort: http-stomp-ws
    {{- end }}
    {{- if .Values.rabbitmqMQTTPlugin.enabled }}
    - name: tcp-mqtt
      protocol: TCP
      port: 1883
      targetPort: tcp-mqtt
    - name: tcp-mqtt-ssl
      protocol: TCP
      port: 8883
      targetPort: tcp-mqtt-ssl
    {{- end }}
    {{- if .Values.rabbitmqWebMQTTPlugin.enabled }}
    - name: http-mqtt-ws
      protocol: TCP
      port: 15675
      targetPort: http-mqtt-ws
    {{- end }}
    {{- if .Values.rabbitmqAmqpsSupport.enabled }}
    - name: tcp-amqps
      protocol: TCP
      port: {{ .Values.rabbitmqAmqpsSupport.amqpsNodePort }}
      targetPort: tcp-amqps
    {{- end }}
    {{ if .Values.prometheus.exporter.enabled }}
    - name: tcp-exporter
      protocol: TCP
      port: {{ .Values.prometheus.exporter.port }}
      targetPort: tcp-exporter
    {{ end }}
    {{- if .Values.rabbitmqPrometheusPlugin.enabled }}
    - name: tcp-metrics
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" "LoadBalancer" }}
      nodePort: {{ .Values.rabbitmqPrometheusPlugin.nodePort }}
      {{- end }}
      port: {{ .Values.rabbitmqPrometheusPlugin.port }}
      targetPort: tcp-metrics
    {{- end }}
  selector:
    app: {{ template "rabbitmq-ha.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
